---

# Test with: curl --data "language=en-US&text=a simple test" http://localhost:8081/v2/check

networks:
  # A network that can not reach anything else
  languagetool_isolated_network:
    internal: true

services:
  languagetool:
    # No need to expose the port, it would not work from the internal network anyways
    image: ghcr.io/six-two/languagetool
    container_name: languagetool-isolated
    restart: always
    environment:
      # - langtool_languageModel=/ngrams
      # Increase minimum and maximum heap size to prevent crashes
      - Java_Xms=512m
      - Java_Xmx=2g
      # - /path/to/ngrams/data:/ngrams
      # - /path/to/logback.xml:/LanguageTool/logback.xml:ro
    # We deploy languagetool in an isolated network, that can not reach the internet
    networks:
      - languagetool_isolated_network
    # This allows you to add your custom languagetool wordlists
    volumes:
      - "$HOME/.config/languagetool:/share:ro"

  # Simple reverse proxy that is dual homed. It ensures that we can reach languagetool-isolated, although it is in an isolated network
  proxy:
    image: ghcr.io/six-two/nginx-reverse-proxy
    container_name: languagetool-isolated-proxy
    restart: always
    ports:
      - "8081:8081"
    environment:
    - LISTEN_PORT=8081
    - BACKEND_HOST=languagetool-isolated
    - BACKEND_PORT=8010
    networks:
      - default
      - languagetool_isolated_network
    depends_on:
      - languagetool

